### ISSUE TITLE
[Fabric 1.20.4] Crashed when Jungle Chest is loaded in world

### ISSUE THREAD

**Issue by benskywalker** [HexagonNico/UndergroundJungle#17] opened 2024-01-18 12:55 UTC
The mod crashes in 1.20.4 whenever I discover a jungle temple within render distance.

Error message:

The game crashed whilst ticking entity
Error: java.lang.NoSuchMethodError: 'boolean io.github.hexagonnico.undergroundjungle.blocks.TempleChestBlockEntity.method_11283(net.minecraft.class_2487)'

Crash Report:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-01-18 07:51:29
Description: Ticking entity

java.lang.NoSuchMethodError: 'boolean io.github.hexagonnico.undergroundjungle.blocks.TempleChestBlockEntity.method_11283(net.minecraft.class_2487)'
	at io.github.hexagonnico.undergroundjungle.blocks.TempleChestBlockEntity.method_11014(TempleChestBlockEntity.java:93)
	at net.minecraft.class_3499.method_15172(class_3499.java:262)
	at net.minecraft.class_3781.method_16626(class_3781.java:134)
	at net.minecraft.class_3790.method_27236(class_3790.java:89)
	at net.minecraft.class_3790.method_14931(class_3790.java:85)
	at net.minecraft.class_3449.method_14974(class_3449.java:100)
	at net.minecraft.class_2794.method_38265(class_2794.java:320)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:319)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.method_12154(class_2806.java:252)
	at net.minecraft.class_3898.method_17225(class_3898.java:671)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:660)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.hexagonnico.undergroundjungle.blocks.TempleChestBlockEntity.method_11014(TempleChestBlockEntity.java:93)
	at net.minecraft.class_3499.method_15172(class_3499.java:262)
	at net.minecraft.class_3781.method_16626(class_3781.java:134)
	at net.minecraft.class_3790.method_27236(class_3790.java:89)
	at net.minecraft.class_3790.method_14931(class_3790.java:85)
	at net.minecraft.class_3449.method_14974(class_3449.java:100)
	at net.minecraft.class_2794.method_38265(class_2794.java:320)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_2794.method_12102(class_2794.java:319)
	at net.minecraft.class_2806.method_51375(class_2806.java:108)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at net.minecraft.class_2806.method_12154(class_2806.java:252)
	at net.minecraft.class_3898.method_17225(class_3898.java:671)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:660)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)

-- Entity being ticked --
Details:
	Entity Type: underground_jungle:jungle_zombie (io.github.hexagonnico.undergroundjungle.entities.JungleZombie)
	Entity ID: 8072
	Entity Name: Jungle Zombie
	Entity's Exact location: -699.50, 3.88, -1709.50
	Entity's Block location: World: (-700,3,-1710), Section: (at 4,3,2 in -44,0,-107; chunk contains blocks -704,-64,-1712 to -689,319,-1697), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,-64,-2048 to -513,319,-1537)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:495)
	at net.minecraft.class_3218.method_31420(class_3218.java:399)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by HexagonNico** [comment] 2024-01-18 16:45
Duplicate of #14

**Closed** 2024-01-18 16:45 UTC

**Comment by benskywalker** [comment] 2024-01-18 16:56
I think these are different bugs as they come from a different line in TempleChestBlockEntity.java, and present differently. While #14 describes a crash on opening a chest, #17 appears when any jungle temple is within render distance; I can't ever see the temple without this crash
