### ISSUE TITLE
[Fabric 1.20.4] Crashed when I tried to open Jungle Chest

### ISSUE THREAD

**Issue by kingkuys2123** [HexagonNico/UndergroundJungle#14] opened 2024-01-02 06:12 UTC
Minecraft 1.20.4
Fabric 0.15.3
Fabric API 0.91.3
Java 20.0.2
Underground Jungle 2.2.1

## **ISSUES**
 - Crashed when I tried to open the Jungle Chest

## **LOG**
```
[13:54:28] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'boolean io.github.hexagonnico.undergroundjungle.blocks.TempleChestBlockEntity.method_11286(net.minecraft.class_2487)'
	at io.github.hexagonnico.undergroundjungle.blocks.TempleChestBlockEntity.method_11007(TempleChestBlockEntity.java:102) ~[undergroundjungle-1.20-2.2.1-fabric.jar:?]
	at net.minecraft.class_2586.method_38244(class_2586.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_38242(class_2586.java:64) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_20598(class_2818.java:388) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.redirect$zna000$c2me-threading-chunkio$onChunkGetPackedBlockEntityNbt(class_2852.java:2606) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:328) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17228(class_3898.java:852) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_39925(class_3898.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.c2me$runOneChunkAutoSave(class_3898.java:8396) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:10416) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:757) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by HexagonNico** [comment] 2024-01-20 10:54
Fixed by 1cde5848bea33f9e501683eb890cc117053144c0

It was caused by method renames that happened in `1.20.3`. There is now a `20.3.0` version that is compatible with `1.20.3` and `1.20.4`

Sorry this took so long, but I was having trouble configuring the project for `1.20.3`.

I think I will also have to update Phantom Loader to support version ranges instead of single versions.

**Closed by HexagonNico** 2024-01-20 10:54 UTC
Labels: Bug, Crash
